README.md
docs/source/installation.rst
source/reports/ml_reports/MotifSeedRecovery.py

Minor updates in install instructions:
- show installation with vs without R
- change github link immuneML to be lowercase

Update install instructions

---

source/IO/dataset_import/VDJdbImport.py
source/api/galaxy/build_dataset_yaml.py
source/api/galaxy/build_yaml_from_arguments.py
source/dsl/DefaultParamsLoader.py
test/IO/dataset_import/test_VDJdbImport.py
test/api/galaxy/test_build_dataset_yaml.py
test/dsl/test_importParser.py
test/encodings/distance_encoding/test_TCRdistEncoder.py

Contains:
- a script that makes a YAML for the DatasetGenerationTool, to be used inside Galaxy 'Create dataset' tool, which is necessary for this proposal to update the Create dataset tool: https://docs.google.com/document/d/1k_f4n0eP5V56nSkhYGXDXJrtwZYPp2i-briLPW7wcjc/edit
- Rename VDJDB to VDJdb (for consistency)
- Add default values for 2 parameters in build_yaml_from_arguments.py

Easy Galaxy dataset generation 

---

source/api/galaxy/build_dataset_yaml.py
test/api/galaxy/test_build_dataset_yaml.py

the script now creates a full yaml with DatasetGeneration instruction

update build_dataset_yaml script 

---

source/config/default_params/reports/motif_seed_recovery_params.yaml
source/reports/hyperparameter/MLSubseqPerformance.py
source/reports/ml_reports/MotifSeedRecovery.py
test/reports/ml_reports/test_motifSeedRecovery.py

- added a missing check to MLSubseqPerformance
- corrected calculating score for motifs with differently sized gaps

Report fixes

---

source/api/galaxy/build_yaml_from_arguments.py
source/config/default_params/reports/coefficients_params.yaml
source/reports/hyperparameter/MLSettingsPerformance.py
source/reports/ml_reports/Coefficients.py

- added linebreak in y axis label mlsettingsperformance 
- change default params for coefficients plot (so that the coefs are actually visible in the plot)

minor updates plots

---

source/encodings/reference_encoding/MatchedRegexRepertoireEncoder.py
source/reports/Report.py
source/reports/encoding_reports/Matches.py

Some small improvements to error messages, based on Chakri's issue

Improved error messages

---

source/IO/dataset_import/AIRRImport.py
source/IO/dataset_import/GenericImport.py
source/IO/dataset_import/MiXCRImport.py
source/IO/dataset_import/OLGAImport.py
source/IO/dataset_import/SingleLineReceptorImport.py
source/IO/dataset_import/TenxGenomicsImport.py
source/IO/dataset_import/VDJdbImport.py
source/util/AdaptiveImportHelper.py
source/util/ImportHelper.py
test/IO/dataset_import/test_AIRRImport.py
test/IO/dataset_import/test_OLGAImport.py
test/IO/dataset_import/test_VDJdbImport.py

This solves some issues I had with various files on galaxy:
- generally, safer import: before doing something with a column, check if the column exists and assume None values may be present in the column
- loading chains from genes added to some importers where it wasn't done yet
- added a test with a 'minimal' AIRR input file to make sure nothing breaks with missing non-critical columns

Small fixes: even more import updates... :P

---

source/config/default_params/reports/ml_settings_performance_params.yaml
source/reports/PlotlyUtil.py
source/reports/hyperparameter/MLSettingsPerformance.py
test/reports/ml_reports/test_mLSettingsPerformance.py

publication-ready figure can now be made directly from the report

small updates MLSettingsPerformance plot

---

source/util/ImportHelper.py
test/IO/dataset_import/test_VDJdbImport.py

assume value in v_genes column can be None (happens in galaxy when retrieving VDJdb files) and add test for this in case it breaks in the future.

minor import  fix for Galaxy

---

docs/source/developer_docs.rst

developer docs page & menu

---

setup.py
source/ml_methods/DeepRC.py
source/reports/ml_reports/TCRdistMotifDiscovery.py
source/util/TCRdistHelper.py

moved import statements from tcrdist/deeprc inside classes/functions
I tested this by pip installing this branch and running quickstart, it works

move optional import statements inside classes

---

immuneML/dsl/InstructionParser.py
immuneML/dsl/instruction_parsers/MLApplicationParser.py
immuneML/workflows/instructions/ml_model_application/MLApplicationInstruction.py
test/integration_tests/test_ML_import_export.py

to be consistent with other instructions

minor update: rename pool_size to number_of_processes in MLApplicationInstruction

---

docs/source/troubleshooting.rst
docs/source/usecases/benchmarking_use_case.rst
docs/source/usecases/emerson_replication.rst
docs/source/usecases/extendability_use_case.rst
immuneML/IO/dataset_export/PickleExporter.py

- added NIRD links to docs
- pickleexporter: also export python version and pickle protocol in info.txt

Small updates

---

README.md
immuneML/encodings/deeprc/DeepRCEncoder.py
immuneML/reports/ml_reports/DeepRCMotifDiscovery.py
requirements_DeepRC.txt

- set sequence templates to 1 if it is None
- hardcode widis-lstm-tools commit
- add version numbers of deeprc/widis-lstm-tools dependencies in the readme

Deeprc quickfix

---

immuneML/encodings/distance_encoding/CompAIRRDistanceEncoder.py
immuneML/ml_methods/util/Util.py
immuneML/reports/encoding_reports/FeatureComparison.py
immuneML/util/CompAIRRHelper.py

2 small fixes:
- FeatureComparison report: determine axis max values after filtering
- CompAIRRHelper: bugfix in making repertoire file (file header did in some cases not match content)

Minor bugfixes

---

immuneML/api/galaxy/DataSimulationTool.py
immuneML/api/galaxy/DatasetGenerationTool.py
immuneML/api/galaxy/GalaxySimulationTool.py
immuneML/api/galaxy/GalaxyYamlTool.py
immuneML/api/galaxy/Util.py
immuneML/api/galaxy/build_yaml_from_arguments.py
test/api/galaxy/test_DataSimulationTool.py
test/api/galaxy/test_DatasetGenerationTool.py
test/api/galaxy/test_GalaxyYamlTool.py

for automatic compatibility with other tools
I only added this change to tools which are capable of generating new datasets

update: make standard dataset name in GalaxyTools 'dataset' 

---

immuneML/hyperparameter_optimization/core/HPSelection.py
immuneML/workflows/instructions/TrainMLModelInstruction.py

Adresses the bug William described

2 fixes for bugs that only showed up on Windows

---

immuneML/encodings/abundance_encoding/AbundanceEncoderHelper.py
immuneML/encodings/abundance_encoding/CompAIRRSequenceAbundanceEncoder.py

Add caching for fisher p-value computation

Speed up CompAIRRSequenceAbundance encoder

---

immuneML/dsl/instruction_parsers/TrainMLModelParser.py
immuneML/encodings/preprocessing/FeatureScaler.py
immuneML/ml_methods/SklearnMethod.py
immuneML/ml_methods/util/Util.py
immuneML/ml_metrics/Metric.py
immuneML/reports/ml_reports/TrainingPerformance.py

previous error message was very generic (key F1 not defined), the new error message shows explicitly a list of valid options

improved error message for Metric

---

immuneML/ml_methods/generative_models/SoNNia.py

- In this PR I'm removing binaries (H5 file) from files exported while training Sonnia model. Instead, I'm saving model configuration and weights in json format.
- Sonnia is based on Keras Functional model, which doesn't support yaml (ref: https://www.tensorflow.org/api_docs/python/tf/keras/models/model_from_yaml). Thus, I decided to go with json format.
- Model is loaded by initiating the object with the use of architecture given in model_overview.yaml file and by setting weights stored in model.json file. I decided to take this approach since Sonnia is using additional custom layers, which Keras struggles to unpack.

Remove binary H5 file from Sonnia
