source/dsl/instruction_parsers/TrainMLModelParser.py
source/reports/ml_reports/MotifSeedRecovery.py
source/workflows/instructions/MLProcess.py

- Bugfix MotifSeedRecovery: extra check in check\_prerequisites
- remove newline from 'evaluating hyperparameter setting' print statement so every HP setting evaluation ends up nicely in one block in the printed results
- extra ParameterValidator checks for TrainMLModel instruction (should make it easier for the user to detect when they misunderstand what should be filled in, especially string/list values)

Small fixes

---

source/api/galaxy/build_dataset_yaml.py

this is necessary when Radka starts implementing updates to the 'Create dataset' tool I suggested (based on sequence import refactoring)
implementation comes later, but this way she can finish her part without errors

Mini change: Add metadata columns argument

---

docs/source/galaxy/how_to_make_an_immuneML_dataset_in_galaxy.rst

Updated the docs based on the new Create dataset interface (simple/advanced) and refactored sequence import
The docs now start with a little introduction about galaxy collections and immuneML datasets, and then explains both the simple and advanced interface
For the advanced interface I added an example of how to import a ReceptorDataset as well

Updated docs 'How to make an immuneML dataset in Galaxy'

---

source/api/galaxy/build_dataset_yaml.py
source/api/galaxy/build_yaml_from_arguments.py
source/data_model/cell/CellList.py
source/data_model/receptor/BCKReceptor.py
source/data_model/receptor/ChainPair.py
source/data_model/receptor/ReceptorBuilder.py
source/data_model/receptor/receptor_sequence/ReceptorSequenceList.py
source/reports/ml_reports/CoefficientPlottingSettingList.py
source/util/ImportHelper.py
test/api/galaxy/test_build_dataset_yaml.py

-> add metadata column mapping for simple create dataset galaxy interface. for now the column name is used both as key and value (i.e. label corresponds directly to original column name), as I think this is easiest to understand for the user
-> write warnings to logger, and import MutableSequence from collections.abc to remove deprecationwarning
-> do not sort ChainPair (gave bug when TRG_TRD was selected)
-> added BCReceptor with kappa chain (now named BCKReceptor, can be changed if necessary..) because it is present in 10xGenomics files

small fixes related to galaxy interfaces

---

source/IO/dataset_import/IRISImport.py
source/IO/dataset_import/SingleLineReceptorImport.py
source/util/ImportHelper.py
test/IO/dataset_import/test_AIRRImport.py
test/IO/dataset_import/test_IGoRImport.py
test/IO/dataset_import/test_ImmunoSEQRearrangementImport.py
test/IO/dataset_import/test_OLGAImport.py
test/IO/dataset_import/test_genericImport.py
test/IO/dataset_import/test_immunoSEQSampleImport.py
test/IO/dataset_import/test_miXCRImport.py
test/dsl/test_importParser.py

Discover sequence/receptor files with any extension (assume the data folder shouldn't contain irrelevant files)
Clearer error messages when wrong file happens to be in the receptor data folder (for example if someone accidentally has a metadata file there)
Updated tests: make sure input data for sequence/receptor datasets is in its own folder and does not contain other (metadata) files

Receptor file discovery

---

source/workflows/instructions/exploratory_analysis/ExploratoryAnalysisInstruction.py
test/integration_tests/test_exploratoryAnalysisDesignMatrixExporter.py
test/workflows/instructions/test_exploratoryAnalysisInstruction.py

previously data files were in the same folder as report outputs, now they are in their own subfolders

Small fix: add subfolders in exploratory analysis output

---

source/dsl/ImmuneMLParser.py
source/workflows/instructions/quickstart.py

do not check column_mapping and metadata_column_mapping dict keys. This is necessary for the Create Dataset galaxy tool when using it with VDJdb input, because it contains columns that have . or ' ' inside their names, which could be used for the metadata column mapping.

do not check column_mapping and metadata_column_mapping dicts

---

docs/source/FAQ.rst
docs/source/installation/install_with_package_manager.rst
requirements.txt
setup.py
source/encodings/deeprc/DeepRCEncoder.py
source/ml_methods/DeepRC.py

Addresses this trello card: https://trello.com/c/gqK6DsfW/312-look-into-whether-it-could-be-easy-to-separate-tcrdist-and-deeprc-from-the-core-installation-procedure-to-have-them-as-add-ons-m
- DeepRC and TCRDist are now by default not installed, but can be added. 
- Installation documentation has been updated 
- Installation docs is also now written to a version with and without R, to make it clearer
- Even more proof that this separation of dependencies is necessary: I encountered a bug when installing the TCRDist dependencies on Mac. In other words, installing the current version of immuneML did not work without errors! But now that TCRDist is optional, that bug only occurs when explicitly adding TCRDist. I tried to find a fix for this (automatically installing other packages), but did …

Small fix: optional DeepRC/TCRDist dependencies

---

immuneML/api/galaxy/build_dataset_yaml.py

if no metadata mapping is given, use the default one (e.g, VDJdb format)

super small fix: dont overwrite metadata column mapping if not given in Galaxy

---

immuneML/presentation/html/ExploratoryAnalysisHTMLBuilder.py
immuneML/presentation/html/Util.py
immuneML/presentation/html/templates/ExploratoryAnalysis.html
immuneML/reports/ReportResult.py
immuneML/reports/encoding_reports/Matches.py
test/presentation/html/test_ExploratoryAnalysisHTMLBuilder.py

- List downloadable tables
- Put encoding params in a table instead of printing the dict
Also removes output_text and other_output lists from ReportResult since they are not being used in any report so far

Improve readability of ExploratoryAnalysis HTML

---

immuneML/IO/dataset_export/AIRRExporter.py
immuneML/data_model/repertoire/Repertoire.py
immuneML/preprocessing/filters/CountPerSequenceFilter.py
immuneML/preprocessing/filters/DuplicateSequenceFilter.py
immuneML/util/ImportHelper.py
immuneML/util/RepertoireBuilder.py

re-use original repertoire filenames for output filenames (Pickle/AIRR) instead of UUID (but keep UUID as identifier)
The suffix '_data' has been removed from the internal npy files, so that this filename can be used as a base for determining the output filename. 
Filtered repertoires (which may contain slightly different content) will receive the suffix '_filtered' to their original name

Repertoire filenames instead of UUID

---

immuneML/IO/dataset_import/AIRRImport.py
immuneML/IO/dataset_import/DatasetImportParams.py
immuneML/IO/dataset_import/GenericImport.py
immuneML/IO/dataset_import/IGoRImport.py
immuneML/IO/dataset_import/IReceptorImport.py
immuneML/IO/dataset_import/ImmunoSEQRearrangementImport.py
immuneML/IO/dataset_import/ImmunoSEQSampleImport.py
immuneML/IO/dataset_import/MiXCRImport.py
immuneML/IO/dataset_import/SingleLineReceptorImport.py
immuneML/IO/dataset_import/TenxGenomicsImport.py
immuneML/IO/dataset_import/VDJdbImport.py
immuneML/config/default_params/datasets/immuno_seq_rearrangement_params.yaml
immuneML/util/ImportHelper.py
test/IO/dataset_import/test_ImmunoSEQRearrangementImport.py

Added 'column_mapping_synonyms' to define alternative names for columns. Formatting is the same as column_mapping and metadata_column_mapping. The behavior remains the same if column_mapping_synonyms is not specified. This allows for automatic import of immunoSEQ rearrangment files of analyzer 3.0.
Initially, columns are mapped as usual. If some immuneML column is missing in the resulting dataframe, but a synonym is present in column_mapping_synonyms, the mapping is applied for that column.
Also moved some functionalities in importhelper into separate functions, and updated usecols when loading a dataframe;
- first attempt usecols = columns_to_load + column_mapping keys + column_mapping_synonyms keys + metadata_column mapping keys
- if this fails, attempt usecols = columns_to_load
- if …

column_mapping_synonyms

---

immuneML/config/default_params/encodings/distance_params.yaml
immuneML/encodings/distance_encoding/DistanceEncoder.py
immuneML/util/DistanceMetrics.py
test/encodings/distance_encoding/test_distanceEncoder.py
test/pairwise_repertoire_comparison/test_pairwiseRepertoireComparison.py

- inverse jaccard (distance) instead of jaccard (similarity)
- bugfix: 'name' and 'context' params were not passed to init
- updated default params
- updated docs

Bugfixes in DistanceEncoder

---

immuneML/util/ImportHelper.py

This was an edge case that happened in some adaptive files. In the input file a sequence would be length 2 (for example 'TF'). Then after trimming leading and trailing amino acids, the remaining sequence would be length 0. But this happens after applying "standardize none values", meaning some empty sequences are None, and some "". With this fix, "" sequences are also removed upon import.

bugfix: if sequence is string of length 0 but not None, this is also considered 'empty'

---

immuneML/IO/dataset_export/ImmuneMLExporter.py
immuneML/api/galaxy/build_yaml_from_arguments.py

- recursively parse dicts in immuneMLExport
- remove metadata file from yaml for simplified interface as it caused errors for receptor datasets

Bugfixes for Galaxy tools

---

immuneML/dsl/instruction_parsers/ExploratoryAnalysisParser.py
immuneML/dsl/instruction_parsers/LabelHelper.py
immuneML/dsl/instruction_parsers/TrainMLModelParser.py
immuneML/environment/Constants.py

I moved the label processing code from TrainMLModelParser to a common LabelHelper class, so it can be used by multiple instructions. The original label processing code in ExploratoryAnalysis was too simple to deal with label positive_class definitions (necessary when testing SequenceAbundance encoder in expl. analysis). Now both TrainMLModelParser and ExploratoryAnalysisParser use LabelHelper to construct their LabelConfiguration.

Bugfix: label positive_class could not be defined in exploratory analysis

---

immuneML/config/default_params/reports/feature_comparison_params.yaml
immuneML/reports/encoding_reports/FeatureComparison.py
test/reports/encoding_reports/test_featureComparison.py

added keep_fraction option to FeatureComparison report; plot only the fraction of the features differing most across differently labeled repertoires/sequences

keep_fraction option for FeatureComparison

---

docs/source/installation/install_with_package_manager.rst
docs/source/troubleshooting.rst

added description for temporary workaround with old version of setuptools
included in troubleshooting both under "installation issues" (warnings happen, and the final installed version of immuneML doesn't work) and "runtime errors" (in case warnings during installation are overlooked)

docs temporary workaround with old version of setuptools

---

docs/source/quickstart/cli_yaml.rst

A master student pointed out we are using 2 different filenames for the quickstart yaml, fixed here

small fix in docs

---

immuneML/util/ImportHelper.py

change error into warning, so files are not always required to contain both amino acid and nt sequences (now it fails for Generic import when only aa sequence is present)

small fix in import

---

immuneML/IO/dataset_import/GenericImport.py
immuneML/config/default_params/datasets/generic_params.yaml
immuneML/encodings/evenness_profile/EvennessProfileEncoder.py
immuneML/encodings/kmer_frequency/KmerFrequencyEncoder.py
immuneML/encodings/onehot/OneHotEncoder.py
immuneML/encodings/reference_encoding/MatchedReceptorsEncoder.py
immuneML/encodings/reference_encoding/MatchedReferenceUtil.py
immuneML/encodings/reference_encoding/MatchedRegexEncoder.py
immuneML/encodings/reference_encoding/MatchedSequencesEncoder.py
immuneML/encodings/word2vec/Word2VecEncoder.py
immuneML/util/EncoderHelper.py

- specify default params for Generic import: When they are not present, the default params are actually 'None', which leads to confusing behavior because we don't handle it explicitly (e.g., <if param> behaves as <if False>, when param was not explicitly set to False). Generic import behavior is more sensible when default params are the same as for all other importers.
- Do not catch *any* error during Encoder.build_object (misleading error when building the encoder fails for a different reason than specifying the wrong Dataset type). Instead, have one 'dataset type' check for all encoders using dataset_mapping, then run the rest of the Encoder.build_object code. 
- Added assert statement to fail early when references were not successfully imported (len(references)==0) in …

Minor fixes

---

immuneML/config/default_params/encodings/comp_airr_sequence_abundance_params.yaml
immuneML/encodings/abundance_encoding/CompAIRRSequenceAbundanceEncoder.py
immuneML/reports/data_reports/SignificantFeatures.py
immuneML/util/SignificantFeaturesHelper.py
test/encodings/filtered_sequence_encoding/test_CompAIRRSequenceAbundanceEncoder.py

remove memory-heavy instance variables from CompAIRRSequenceAbundance object, this massively decreases the memory usage when training ML models (when multiple encoder objects are made and stored in memory)

bugfix: Compairr seq abundance memory

---

immuneML/IO/dataset_import/AIRRImport.py
immuneML/IO/dataset_import/GenericImport.py
immuneML/IO/dataset_import/IGoRImport.py
immuneML/IO/dataset_import/ImmunoSEQRearrangementImport.py
immuneML/IO/dataset_import/ImmunoSEQSampleImport.py
immuneML/IO/dataset_import/MiXCRImport.py
immuneML/IO/dataset_import/OLGAImport.py
immuneML/IO/dataset_import/TenxGenomicsImport.py
immuneML/IO/dataset_import/VDJdbImport.py

didn't change any code, but made the docs more accurate: updated class documentation for importers, describing that sequence-level metadata can also be set for repertoires for reports (Olav will use this)

small docs updates for importers

---

immuneML/IO/dataset_import/DataImport.py
immuneML/data_model/AIRRSequenceSet.py
immuneML/data_model/datasets/ElementDataset.py
immuneML/dsl/import_parsers/ImportParser.py
immuneML/encodings/onehot/OneHotEncoder.py
immuneML/environment/Constants.py
immuneML/environment/EnvironmentSettings.py
immuneML/simulation/dataset_generation/RandomDatasetGenerator.py
immuneML/util/AdaptiveImportHelper.py
immuneML/util/CompAIRRHelper.py
immuneML/util/ImportHelper.py
immuneML/workflows/instructions/train_gen_model/TrainGenModelInstruction.py
test/IO/dataset_import/test_AIRRImport.py
test/IO/dataset_import/test_ImmunoSEQRearrangementImport.py
test/api/galaxy/test_GalaxyTrainMLModel.py
test/encodings/filtered_sequence_encoding/test_CompAIRRSequenceAbundanceEncoder.py
test/encodings/motif_encoding/test_SimilarToPositiveSequenceEncoder.py
test/integration_tests/test_dataset_export_html_output.py

- In DataImport.import_dataset, a proper 'complete' dataset_metadata file is now created
- slight reorganisation in DataImport, split into smaller methods for readability
- critical fix in filter_illegal_sequences: do not filter if 'productive' and 'vj_in_frame' are incorrectly specified or some values are set to null. better to import all data with a warning than to silently remove it all

Bugfix: being able to read in previously exported element datasets
